name: Run Tests

on:
  pull_request:
    paths:
      - '.github/scripts/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 markdown unittest-xml-reporting

      - name: Run tests
        env:
          NEWT_SPACE_UID: test_space
          NEWT_APP_UID: test_app
          NEWT_API_TOKEN: test_token
          NEWT_ARTICLE_MODEL_UID: test_article_model
        run: |
          cd .github/scripts/tests
          python -m unittest discover -v
